workflows:
  build-ios:
    name: build ios
    max_build_duration: 120
    instance_type: mac_mini_m1
    triggering:
      events:
        - push
        - pull_request
        - tag
    scripts:
      - name: Build IOS
        script: flutter build ios
    artifacts:
      - build/**/outputs/**/*.aab
    publishing: 
      email:
        recipients:
          - imanhavangi20@gmail.com